begin;

create extension if not exists pgcrypto;

create table if not exists public.answer_review_queue (
    id bigint generated by default as identity primary key,
    word text not null,
    word_key text not null,
    group_id integer null,
    standard_answers text null,
    user_answer_raw text not null,
    user_answer_normalized text not null,
    user_id text not null,
    user_name text null,
    test_mode text null,
    status text not null default 'pending',
    occur_count integer not null default 1,
    review_note text null,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    reviewed_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (word_key, user_answer_normalized, user_id)
);

create table if not exists public.accepted_rules (
    id bigint generated by default as identity primary key,
    word_key text not null,
    answer_text text not null,
    rule_type text not null,
    is_active boolean not null default true,
    review_note text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (word_key, answer_text, rule_type)
);

create table if not exists public.admin_config (
    id bigint generated by default as identity primary key,
    secret_hash text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.answer_review_queue enable row level security;
alter table public.accepted_rules enable row level security;
alter table public.admin_config enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.answer_review_queue to anon, authenticated;
grant select on table public.accepted_rules to anon, authenticated;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'answer_review_queue'
          and policyname = 'answer_review_queue_insert_public'
    ) then
        create policy answer_review_queue_insert_public
            on public.answer_review_queue
            for insert
            to anon, authenticated
            with check (true);
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public'
          and tablename = 'accepted_rules'
          and policyname = 'accepted_rules_select_public'
    ) then
        create policy accepted_rules_select_public
            on public.accepted_rules
            for select
            to anon, authenticated
            using (is_active = true);
    end if;
end
$$;

create or replace function public.bump_answer_review_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    new.last_seen_at = coalesce(new.last_seen_at, now());
    if tg_op = 'UPDATE' then
        new.occur_count = greatest(coalesce(old.occur_count, 1), coalesce(new.occur_count, 1));
    end if;
    return new;
end;
$$;

drop trigger if exists trg_answer_review_queue_updated_at on public.answer_review_queue;
create trigger trg_answer_review_queue_updated_at
before update on public.answer_review_queue
for each row
execute function public.bump_answer_review_queue_updated_at();

create or replace function public.bump_accepted_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_accepted_rules_updated_at on public.accepted_rules;
create trigger trg_accepted_rules_updated_at
before update on public.accepted_rules
for each row
execute function public.bump_accepted_rules_updated_at();

create or replace function public.bump_admin_config_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_admin_config_updated_at on public.admin_config;
create trigger trg_admin_config_updated_at
before update on public.admin_config
for each row
execute function public.bump_admin_config_updated_at();

create or replace function public.verify_admin_secret(input_secret text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    matched boolean;
begin
    select exists(
        select 1
        from public.admin_config
        where is_active = true
          and secret_hash = encode(extensions.digest(input_secret, 'sha256'), 'hex')
    ) into matched;

    return jsonb_build_object('valid', matched);
end;
$$;

grant execute on function public.verify_admin_secret(text) to anon, authenticated;

comment on table public.admin_config is '管理员密钥哈希表，请插入 sha256 后的十六进制字符串。';

commit;
